{"uuid": "cdba6b33-b9e8-4d1b-93f5-94b74fe6593a", "children": ["bbd92cf2-f6cd-43fc-b86b-e398124b4ed6"], "befores": [{"name": "log_on_failure", "status": "passed", "start": 1707975131017, "stop": 1707975131017}], "afters": [{"name": "log_on_failure::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=121.0.6167.160)\nStacktrace:\n#0 0x55c942f7cd93 <unknown>\n#1 0x55c942c60337 <unknown>\n#2 0x55c942c36a18 <unknown>\n#3 0x55c942cd6ead <unknown>\n#4 0x55c942ceca95 <unknown>\n#5 0x55c942cce1e3 <unknown>\n#6 0x55c942c9e135 <unknown>\n#7 0x55c942c9f13e <unknown>\n#8 0x55c942f40e4b <unknown>\n#9 0x55c942f44dfa <unknown>\n#10 0x55c942f2d6d5 <unknown>\n#11 0x55c942f45a6f <unknown>\n#12 0x55c942f1169f <unknown>\n#13 0x55c942f6a098 <unknown>\n#14 0x55c942f6a262 <unknown>\n#15 0x55c942f7bf34 <unknown>\n#16 0x7f8669c94ac3 <unknown>\n\n", "trace": "  File \"/home/shashi/PycharmProjects/pythonSelenium/.venv/lib/python3.10/site-packages/allure_commons/_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/home/shashi/PycharmProjects/pythonSelenium/.venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 932, in _teardown_yield_fixture\n    next(it)\n  File \"/home/shashi/PycharmProjects/pythonSelenium/testCases/conftest.py\", line 43, in log_on_failure\n    allure.attach(driver.get_screenshot_as_png(), name='failed_test', attachment_type=AttachmentType.PNG)\n  File \"/home/shashi/PycharmProjects/pythonSelenium/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 832, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode(\"ascii\"))\n  File \"/home/shashi/PycharmProjects/pythonSelenium/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 843, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)[\"value\"]\n  File \"/home/shashi/PycharmProjects/pythonSelenium/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"/home/shashi/PycharmProjects/pythonSelenium/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1707975131072, "stop": 1707975131075}], "start": 1707975131016, "stop": 1707975131075}